logging:
  level.org.springframework: INFO
  level.com.at: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
---
spring:
  profiles: mem  
  datasource:
    url: jdbc:hsqldb:mem:dataSource
    username: sa
    password:

    #-Dspring.profiles.active=mem